### ISSUE TITLE
WoW Classic compatibility

### ISSUE THREAD

**Issue by mixxorz** [mixxorz/Glass#45]

**Comment by mixxorz** [comment]
From Curse:

> Really loving the look of your addon. Im trying it out on Classic (fully aware that it is made for retail) and i am having an issue with the editbox not appearing. So I disabled all other addons which resulted in the addon not loading at all. I have no idea what is wrong but i get some error messages. The first one is saying: " attempt to index upvalue 'QuickJoinToastButton' (a nil value)", and the second is saying: "Interface\AddOns\Glass\Glass\Modules\EditBox.lua:41: attempt to index field '?' (a nil value)". I hope you find the time to turn it into a Classic addon as well at some point :-)
Cheers

**Comment by mjrmyke** [comment]
I stopped receiving LUA errors by commenting out references to UI elements not in classic. Namely:

* line 57 and 58 in `MainContainer.lua`
* line 41-43 and line 48-50 in `EditBox.lua`

I still can't see my chat input but I think that may be due to another addons settings that persists through being disabled.

**Comment by paroyer** [comment]
Yeah probably another addon, mine is way too large but it's there 
![chat](https://user-images.githubusercontent.com/55961555/91645821-b6238400-e9fd-11ea-9b6b-7ac803ef8a36.jpg)
